import streamlit as st
from PIL import Image

# requirements 

from mapping import *


import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

import seaborn as sns 
import plotly_express as px

from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelBinarizer
from sklearn.compose import make_column_transformer

from sklearn.decomposition import PCA
from sklearn.cluster import KMeans 

from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, f1_score


from IPython.display import display, HTML 

css = """
.output {
    flex-direction: row;
}
"""

HTML('<style>{}</style>'.format(css))



data_url = ("data_to_API.csv")

st.markdown("# We will explore the  dataset \"drugs  consumers\" to predict if a student is taking drugs currently or will use it eventually" )
st.markdown("Voici les drogues qui figurent dans notre dataset :")
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; l alcool : <font color = 'red'>3ème plus dangereuse</font> et <font color = 'red'>'dure'</font>", unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; l'amphétamine : <font color = 'red'>5ème plus dangereuse</font> et <font color = 'red'>'dure'</font></p>", unsafe_allow_html=True)      
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; le benzodiazepine : <font color = 'orange'>9ème plus dangereuse</font> et <font color = 'red'>'dure'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; le cannabis : <font color = 'orange'>10ème plus dangereuse</font> mais <font color = 'green'>'douce'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; la cocaine : <font color = 'red'>4ème plus dangereuse</font> et <font color = 'red'>'dure'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; le crack : <font color = 'red'>1ère plus dangereuse</font> et <font color = 'red'>'dure'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; l'ectasy : <font color = 'orange'>7ème plus dangereuse</font> et <font color = 'red'>'dure'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; l'heroin : <font color = 'red'>2ème plus dangereuse</font> et <font color = 'red'>'dure'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; la ketamine : <font color = 'orange'>8ème plus dangereuse</font> et <font color = 'red'>'dure'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; le LSD : <font color = 'orange'>12ème plus dangereuse</font> et <font color = 'red'>'dure'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; la methadone : <font color = 'orange'>14ème plus dangereuse</font> et <font color = 'red'>'dure'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; les champignons magiques or magics Mushrooms : <font color = 'orange'>11ème plus dangereuse</font> et <font color = 'red'>'dure'</font>",unsafe_allow_html=True)
st.markdown("&nbsp;&nbsp;&nbsp;&#x2022; la nicotine : <font color = 'orange'>13ème plus dangereuse</font>",unsafe_allow_html=True)

st.markdown('''
<style>
[data-testid="stMarkdownContainer"] ul{
    padding-left:40px;
}
</style>
''', unsafe_allow_html=True)

st.markdown("You can see a visualisation generated by an ACP which put on the same graph all the individuals of the dataset as points ")

'''@st.cache(allow_output_mutation = True )
def load_model():
    model = '''
    
if st.button("Meet the Palmer Penguins"):
    st.markdown("The data was collected and made available by **[Dr. Kristen Gorman](https://www.uaf.edu/cfos/people/faculty/detail/kristen-gorman.php)** and **[Palmer Station, Antarctica, LTER](https://pal.lternet.edu/)**.")
    #Ballons
    st.balloons()
    
    
    
#code X_train, Y train etc 





    

age = st.number_input('Insert your age ')
st.write('Your age is ', age)

impulsive_score = st.numebr_input('Rate your impulsivity on a scale of 100')
st.write('Your impulsivity score is : ', impulsive_score)

