import streamlit as st
from PIL import Image

# requirements 

from mapping import *


import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

import seaborn as sns 
import plotly_express as px

from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelBinarizer
from sklearn.compose import make_column_transformer

from sklearn.decomposition import PCA
from sklearn.cluster import KMeans 

from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, f1_score


from IPython.display import display, HTML 

css = """
.output {
    flex-direction: row;
}
"""

HTML('<style>{}</style>'.format(css))



data_url = ("data_to_API.csv")

st.markdown("We will explore the  dataset \"drugs  consumers\" to predict if a student is taking drugs currently or will use it eventually" )
st.markdown("You can see a visualisation generated by an ACP which put on the same graph all the individuals of the dataset as points ")

'''@st.cache(allow_output_mutation = True )
def load_model():
    model = '''